version: '2'

tasks:
  build:docker:
    desc: Build the "crankypants-build" image.
    cmds:
      - docker build -t crankypants-build .

  spec:crankypants:
    desc: Run Crankypants specs.
    cmds:
      - crystal spec spec/

  spec:crappy:
    desc: Run Crappy specs.
    cmds:
      - crystal spec crappy/spec/

  spec:
    desc: Run all specs.
    cmds:
      - task: spec:crankypants
      - task: spec:crappy

  spec:e2e:
    desc: Run E2E tests.
    cmds:
      - docker-compose -f docker-compose.tests.yml up --abort-on-container-exit --exit-code-from tests
