---
version: 2
jobs:
  build:
    docker:
      - image: crystallang/crystal:latest

    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: apt-get update && apt-get install -y libsqlite3-dev
      - restore_cache:
          keys:
            - crankypants-shards-{{ checksum "shard.lock" }}
            - crankypants-shards-
      - run:
          name: Install Shards
          command: shards install
      - save_cache:
          key: crankypants-shards-{{ checksum "shard.lock" }}
          paths:
            - lib
      - run:
          name: Run Tests
          command: crystal spec
